function updateProcessingStatus(db, mearec, analysis_name, status, duration_s, error_msg)
% UPDATEPROCESSINGSTATUS  Track the status of an analysis step.
%
%   db.updateProcessingStatus(mearec, 'generateUnits', 'running')
%   db.updateProcessingStatus(mearec, 'generateUnits', 'completed', 3.2)
%   db.updateProcessingStatus(mearec, 'generateUnits', 'failed', 1.1, 'Not enough units')
%
%   Uses parameter_hash to distinguish runs with different parameters.
%   Non-blocking: errors are caught and emitted as warnings.

    arguments
        db RecordingDatabase
        mearec MEArecording
        analysis_name string
        status string {mustBeMember(status, ["pending","running","completed","failed"])}
        duration_s (1,1) double = 0
        error_msg string = ""
    end

    if ~db.IsConnected; return; end

    try
        db.ensureConnected();

        rec_id = db.getRecordingID(mearec.Metadata.InputPath);
        if isempty(rec_id); return; end

        param_hash = paramHash(mearec.Parameters);

        now_str = char(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
        esc = @(s) strrep(char(string(s)), "'", "''");

        if status == "running"
            sql = sprintf([...
                "INSERT INTO processing_status " ...
                "(recording_id, analysis_name, status, parameter_hash, started_at) " ...
                "VALUES (%d, '%s', 'running', '%s', '%s') " ...
                "ON CONFLICT(recording_id, analysis_name, parameter_hash) DO UPDATE SET " ...
                "status='running', started_at='%s', completed_at=NULL, " ...
                "duration_s=NULL, error_message=NULL"], ...
                rec_id, esc(analysis_name), param_hash, now_str, now_str);

        elseif status == "completed"
            sql = sprintf([...
                "INSERT INTO processing_status " ...
                "(recording_id, analysis_name, status, parameter_hash, completed_at, duration_s) " ...
                "VALUES (%d, '%s', 'completed', '%s', '%s', %.4f) " ...
                "ON CONFLICT(recording_id, analysis_name, parameter_hash) DO UPDATE SET " ...
                "status='completed', completed_at='%s', duration_s=%.4f, error_message=NULL"], ...
                rec_id, esc(analysis_name), param_hash, now_str, duration_s, now_str, duration_s);

        elseif status == "failed"
            sql = sprintf([...
                "INSERT INTO processing_status " ...
                "(recording_id, analysis_name, status, parameter_hash, completed_at, duration_s, error_message) " ...
                "VALUES (%d, '%s', 'failed', '%s', '%s', %.4f, '%s') " ...
                "ON CONFLICT(recording_id, analysis_name, parameter_hash) DO UPDATE SET " ...
                "status='failed', completed_at='%s', duration_s=%.4f, error_message='%s'"], ...
                rec_id, esc(analysis_name), param_hash, now_str, duration_s, esc(error_msg), ...
                now_str, duration_s, esc(error_msg));

        else  % pending
            sql = sprintf([...
                "INSERT INTO processing_status " ...
                "(recording_id, analysis_name, status, parameter_hash) " ...
                "VALUES (%d, '%s', 'pending', '%s') " ...
                "ON CONFLICT(recording_id, analysis_name, parameter_hash) DO UPDATE SET " ...
                "status='pending'"], ...
                rec_id, esc(analysis_name), param_hash);
        end

        execute(db.Connection, sql);

    catch ME
        warning('RecordingDatabase:statusUpdateFailed', ...
            'Could not update processing status: %s', ME.message);
    end
end
