function det = selectNoCE(X_feat, responsive_local, subset_responsive, p_outlr)
% SELECTNOCE  No outlier detection — use all responsive units, select CE by distance.

fprintf('Outlier detection disabled: using all %d responsive units\n', numel(responsive_local));
clean_resp_local = responsive_local;
inh_centroid     = mean(X_feat(clean_resp_local, :), 1);

non_responsive_local = find(~subset_responsive);
ce_ratio    = p_outlr.CounterexampleRatio;
n_pick      = min(ce_ratio * numel(clean_resp_local), numel(non_responsive_local));
pool_dists  = pdist2(inh_centroid, X_feat(non_responsive_local, :), 'correlation');
dist_threshold = prctile(pdist2(inh_centroid, X_feat(clean_resp_local, :), 'correlation'), ...
    p_outlr.CounterexampleDistancePercentile);
far_pool = non_responsive_local(pool_dists(:) >= dist_threshold);
if numel(far_pool) < n_pick; far_pool = non_responsive_local; end
n_ce_pool  = numel(far_pool);
perm_order = randperm(numel(far_pool));
counterexample_idx_local = far_pool(perm_order(1:min(n_pick, numel(far_pool))));
fprintf('CE selection (no filtering): %d units from distance pool\n', numel(counterexample_idx_local));

det = struct( ...
    'responsive_local',             responsive_local, ...
    'clean_resp_local',             clean_resp_local, ...
    'counterexample_idx_local',     counterexample_idx_local, ...
    'tf_resp_outlier',              false(1, numel(responsive_local)), ...
    'inh_centroid',                 inh_centroid, ...
    'resp_geom_mask',               logical([]), ...
    'resp_community_outlier_mask',  logical([]), ...
    'resp_purity_outlier_mask',     logical([]), ...
    'ce_outlier_mask',              logical([]), ...
    'ce_distances_from_inh',        pool_dists, ...
    'community_ids',                [], ...
    'inh_comm_ids',                 [], ...
    'Q_modularity',                 NaN, ...
    'use_community_path',           false, ...
    'n_ce_pool',                    n_ce_pool, ...
    'success',                      true);
end
